base_dev_dir: '/home/alien/Research/'

hydra:
  run:
    dir: '${base_dev_dir}/xskill/experiment/label_real_kitchen/${now:%Y-%m-%d_%H-%M-%S}'

exp_path: '/home/alien/Research/xskill/experiment/pretrain/2025-08-12_00-17-19'
save_path: ${exp_path}
ckpt: 299
device: 'cuda:0'



resize_shape: [160,120]
frequency: 3

robot_dataset:
  _target_: xskill.dataset.real_world_pretrain_dataset.RealWorldEpisodeTrajDataset
  _allowed_dirs: [
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0001',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0003',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0004',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0005',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0006',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0007',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0008',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0009',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0010',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0012',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0013',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0014',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0015',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0016',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0017',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0018',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0020',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0021',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0022',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0023',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0024',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0026',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0028',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0029',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0031',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0032',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0033',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0034',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0035',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0037',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0038',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0041',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0042',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0043',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0044',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0045',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0046',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0048',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0049',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0052',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0054',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0057',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0058',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0059',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0060',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0061',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0062',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0063',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0064',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0067',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0069',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0070',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0071',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0073',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0075',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0076',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0077',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0084',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0085',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0086',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0088',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0089',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0091',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0092',
  ]
  frame_sampler:
    _target_: xskill.dataset.frame_samplers.ZarrFrequencySampler
    offset: 0
    num_frames: -1
    frequency: 3
  slide: 8
  max_get_threads: 50
  resize_shape: ${resize_shape}

human_dataset:
  _target_: xskill.dataset.real_world_pretrain_dataset.RealWorldEpisodeTrajDataset
  _allowed_dirs: [
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0001_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0003_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0004_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0005_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0006_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0007_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0008_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0009_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0010_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0012_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0013_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0014_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0015_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0016_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0017_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0018_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0020_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0021_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0022_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0023_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0024_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0026_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0028_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0029_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0031_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0032_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0033_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0034_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0035_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0037_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0038_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0041_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0042_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0043_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0044_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0045_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0046_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0048_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0049_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0052_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0054_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0057_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0058_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0059_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0060_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0061_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0062_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0063_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0064_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0067_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0069_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0070_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0071_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0073_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0075_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0076_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0077_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0084_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0085_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0086_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0088_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0089_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0091_human',
    '${base_dev_dir}/xskill/datasets/rh20T_test/task_0092_human',
  ]
  frame_sampler:
    _target_: xskill.dataset.frame_samplers.ZarrFrequencySampler
    offset: 0
    num_frames: ${robot_dataset.frame_sampler.num_frames}
    frequency: ${robot_dataset.frame_sampler.frequency}
  slide: 8
  max_get_threads: ${robot_dataset.max_get_threads}
  resize_shape: ${resize_shape}

augmentations: ['center_crop_110_146','normalize']

