base_dev_dir: '/home/alien/Research/'

hydra:
  run:
    dir: '${base_dev_dir}/xskill/experiment/label_sim_kitchen/${now:%Y-%m-%d_%H-%M-%S}'

resize_shape: [124,124]
data_path: ${base_dev_dir}/xskill/datasets/kitchen_dataset
exp_path: '/home/alien/Research/xskill/experiment/pretrain/2025-07-01_sim'
ckpt: 79
device: 'cuda:0'
plot_top_k: null
verbose: True